// 대시보드 다국어 라벨 (페이지·리포트·현황판 공유)

export const DASHBOARD_LABELS = {
  ko: {
    title: "내 학습 리포트",
    teacherTitle: "전체 학생 현황",
    parentTitle: "자녀 학습 리포트",
    diagnosis: "진단평가 리포트",
    lessons: "수업 기록",
    noDiagnosis: "아직 진단평가 기록이 없어요.",
    noLessons: "아직 수업 기록이 없어요.",
    noStudents: "연결된 학생이 없어요. 선생님께 문의해 주세요.",
    level: "단계",
    reading: "읽기",
    writing: "글쓰기",
    correct: "정답",
    continueLessons: "수업 계속하기 →",
    signOut: "로그아웃",
    // 리포트 심화
    overall: "종합",
    borderline: "경계선",
    byDomain: "영역별 단계",
    strength: "강점",
    needsWork: "집중 보완",
    nextStep: "다음 단계로 가려면",
    history: "지난 진단 기록",
    // 진도·성취
    progress: "수업 진도",
    passed: "통과",
    retry: "재작성",
    score: "점수",
    recentLessons: "최근 수업",
    stage: "단계",
    lesson: "차시",
    passedOf: (a: number, b: number) => `${a}/${b}차시 통과`,
    // 교사 현황판
    summary: "학생 요약",
    studentName: "학생",
    readingShort: "읽기",
    writingShort: "글쓰기",
    progressCol: "수업 진도",
    lastActive: "최근 활동",
    notStarted: "—",
    students: "명",
  },
  en: {
    title: "My Learning Report",
    teacherTitle: "All Students",
    parentTitle: "My Child's Learning Report",
    diagnosis: "Placement Report",
    lessons: "Lesson History",
    noDiagnosis: "No placement test results yet.",
    noLessons: "No lesson records yet.",
    noStudents: "No linked students yet. Please contact your teacher.",
    level: "Level",
    reading: "Reading",
    writing: "Writing",
    correct: "correct",
    continueLessons: "Continue lessons →",
    signOut: "Sign out",
    overall: "Overall",
    borderline: "borderline",
    byDomain: "By skill area",
    strength: "Strength",
    needsWork: "Focus area",
    nextStep: "To reach the next level",
    history: "Past results",
    progress: "Lesson progress",
    passed: "Passed",
    retry: "Revise",
    score: "Score",
    recentLessons: "Recent lessons",
    stage: "Stage",
    lesson: "Lesson",
    passedOf: (a: number, b: number) => `${a}/${b} passed`,
    summary: "Students",
    studentName: "Student",
    readingShort: "Reading",
    writingShort: "Writing",
    progressCol: "Progress",
    lastActive: "Last active",
    notStarted: "—",
    students: "",
  },
};

export type DashLabels = (typeof DASHBOARD_LABELS)["ko"];
